/**
 * Phase 10 Seed — Pre-Production Hardening & Pilot Readiness
 *
 * Seeds:
 * - 17 go-live gates (all categories)
 * - 15 readiness scorecards (all modules)
 * - 6 pilot defects (honest about demo system state)
 * - 8 migration status items
 * - 1 restore test result (fail — not yet tested)
 * - 30 UAT scripts with steps
 * - 20 security test scenarios
 * - 1 completed security test run with findings
 *
 * DEMO MODE HONESTY: Gates AUTH_SESSION_GUARDS and AUTH_KEYCLOAK_INTEGRATION
 * reflect the actual state — no session guards, no Keycloak configured yet.
 */

import {
  db,
  goLiveGatesTable,
  readinessScorecardTable,
  pilotDefectsTable,
  migrationStatusTable,
  restoreTestResultsTable,
  uatScriptsTable,
  uatTestRunsTable,
  uatTestRunStepsTable,
  securityTestScenariosTable,
  securityTestRunsTable,
  securityTestFindingsTable,
  auditLogsTable,
} from "@workspace/db";
import { eq } from "drizzle-orm";

// ─── GO-LIVE GATES ─────────────────────────────────────────────────────────────

async function seedGoLiveGates() {
  const gates = [
    // AUTH category
    {
      gateCode: "AUTH_SESSION_GUARDS",
      category: "auth",
      titleEn: "Session Authentication Guards Active",
      titleAr: "حراسات المصادقة بالجلسة نشطة",
      descriptionEn: "All API endpoints must enforce session-based authentication. Unauthenticated requests must return 401.",
      severity: "critical",
      status: "warn",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({
        demoMode: true,
        note: "DEMO MODE — no session-based auth guards are active. All API endpoints accept unauthenticated requests by design for the pilot. MUST be remediated before production go-live.",
      }),
      blockerDescriptionEn: "Session authentication guards are NOT active. All API endpoints accept unauthenticated requests in demo mode. This is a critical security gap that must be resolved before production go-live.",
      blockerDescriptionAr: "حراسات المصادقة غير نشطة. جميع نقاط الـ API تقبل الطلبات غير المصادق عليها في وضع العرض.",
      remediationEn: "Add Passport.js or equivalent session middleware. Require req.session.userId on all mutating routes. Wire Keycloak OIDC integration.",
      remediationAr: "أضف برمجية Passport.js للمصادقة. اشترط req.session.userId على جميع مسارات التعديل.",
      sortOrder: 10,
    },
    {
      gateCode: "AUTH_KEYCLOAK_INTEGRATION",
      category: "auth",
      titleEn: "Keycloak SSO Integration Configured",
      titleAr: "تكامل Keycloak SSO مُهيأ",
      descriptionEn: "An approved SSO (Keycloak OIDC or SAML) integration connection profile must exist.",
      severity: "critical",
      status: "fail",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ profilesFound: 0, note: "No approved SSO integration profiles found in integration_connection_profiles." }),
      blockerDescriptionEn: "No approved Keycloak OIDC/SAML integration profile configured. This is required for enterprise SSO authentication.",
      blockerDescriptionAr: "لا يوجد ملف تعريف تكامل SSO معتمد لـ Keycloak.",
      remediationEn: "Create and approve an integration connection profile with integrationType=sso_oidc or sso_saml in the Integration Governance module.",
      remediationAr: "أنشئ ملف تعريف اتصال تكامل SSO واعتمده في وحدة حوكمة التكامل.",
      sortOrder: 20,
    },
    // BACKUP category
    {
      gateCode: "DATA_BACKUP_VERIFIED",
      category: "backup",
      titleEn: "Verified Backup in Last 7 Days",
      titleAr: "نسخة احتياطية موثقة في آخر 7 أيام",
      descriptionEn: "A verified backup must exist within the last 7 days.",
      severity: "critical",
      status: "fail",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ verifiedBackupsInLast7Days: 0 }),
      blockerDescriptionEn: "No verified backup found in the last 7 days. Run and verify a backup before go-live.",
      blockerDescriptionAr: "لم يتم العثور على نسخة احتياطية موثقة في آخر 7 أيام.",
      remediationEn: "Run a full backup via Admin > Backup Records and mark it as verified.",
      remediationAr: "قم بتشغيل نسخة احتياطية كاملة من خلال الإدارة > سجلات النسخ الاحتياطية.",
      sortOrder: 30,
    },
    {
      gateCode: "DATA_RESTORE_TESTED",
      category: "backup",
      titleEn: "Restore Test Passed in Last 30 Days",
      titleAr: "اختبار الاستعادة ناجح في آخر 30 يوماً",
      descriptionEn: "A successful restore test must have been performed within the last 30 days.",
      severity: "critical",
      status: "fail",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ passedRestoreTestsInLast30Days: 0 }),
      blockerDescriptionEn: "No successful restore test found in the last 30 days. Perform a full restore test.",
      blockerDescriptionAr: "لم يتم إجراء اختبار استعادة ناجح في آخر 30 يوماً.",
      remediationEn: "Perform a full restore test and record the result via POST /api/restore-tests.",
      remediationAr: "أجرِ اختبار استعادة كاملاً وسجّل النتيجة.",
      sortOrder: 40,
    },
    {
      gateCode: "BACKUP_SCHEDULE_CONFIGURED",
      category: "backup",
      titleEn: "Backup Schedule Configured",
      titleAr: "جدول النسخ الاحتياطي مُهيأ",
      descriptionEn: "A recurring backup schedule must be configured and operational.",
      severity: "major",
      status: "warn",
      evaluationType: "hybrid",
      evidenceJson: JSON.stringify({ note: "Backup schedule should be verified via system cron or scheduler." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "Configure automated backup schedule in system cron. Verify at least one completed backup exists.",
      remediationAr: "هيّئ جدول النسخ الاحتياطي التلقائي في cron النظام.",
      sortOrder: 50,
    },
    // LICENSING category
    {
      gateCode: "LICENSE_VALID",
      category: "licensing",
      titleEn: "Valid License Active",
      titleAr: "ترخيص صالح نشط",
      descriptionEn: "An active, unexpired license must be present.",
      severity: "critical",
      status: "pending",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "License validation will be evaluated at run time." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "Activate a valid enterprise license via Admin > License.",
      remediationAr: "قم بتفعيل ترخيص مؤسسي صالح عبر الإدارة > الترخيص.",
      sortOrder: 60,
    },
    // CONFIG category
    {
      gateCode: "ORG_CONFIGURED",
      category: "config",
      titleEn: "Organization Configured",
      titleAr: "المنظمة مُهيأة",
      descriptionEn: "At least one active organization must be configured.",
      severity: "critical",
      status: "pending",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "Will be evaluated when gates are run." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "Configure at least one active organization in Admin > Organizations.",
      remediationAr: "هيّئ منظمة نشطة واحدة على الأقل.",
      sortOrder: 70,
    },
    {
      gateCode: "PAYROLL_CONFIGURED",
      category: "config",
      titleEn: "Payroll Salary Grades Configured",
      titleAr: "درجات الرواتب مُهيأة",
      descriptionEn: "At least one active salary grade must be configured.",
      severity: "major",
      status: "pending",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "Will be evaluated when gates are run." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "Configure salary grades in Payroll > Salary Grades.",
      remediationAr: "هيّئ درجات الراتب في الرواتب > درجات الراتب.",
      sortOrder: 80,
    },
    {
      gateCode: "LEAVE_TYPES_CONFIGURED",
      category: "config",
      titleEn: "Leave Types Configured (≥2 active)",
      titleAr: "أنواع الإجازات مُهيأة (2 نشطة على الأقل)",
      descriptionEn: "At least 2 active leave types must be configured.",
      severity: "major",
      status: "pending",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "Will be evaluated when gates are run." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "Configure at least 2 active leave types in Leave > Leave Types.",
      remediationAr: "هيّئ نوعين على الأقل من الإجازات النشطة.",
      sortOrder: 90,
    },
    {
      gateCode: "HOLIDAYS_CONFIGURED",
      category: "config",
      titleEn: "Public Holidays Configured for Current Year",
      titleAr: "الإجازات الرسمية مُهيأة للسنة الحالية",
      descriptionEn: "At least one public holiday must be configured for the current year.",
      severity: "major",
      status: "pending",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "Will be evaluated when gates are run." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "Add public holidays for the current year in Leave > Public Holidays.",
      remediationAr: "أضف الإجازات الرسمية للسنة الحالية.",
      sortOrder: 100,
    },
    {
      gateCode: "DEVICES_ENROLLED",
      category: "config",
      titleEn: "Attendance Devices Enrolled",
      titleAr: "أجهزة الحضور مسجّلة",
      descriptionEn: "At least one active attendance device must be enrolled.",
      severity: "major",
      status: "pending",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "Will be evaluated when gates are run." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "Enroll at least one attendance device in Attendance > Devices.",
      remediationAr: "سجّل جهاز حضور واحد على الأقل.",
      sortOrder: 110,
    },
    {
      gateCode: "APPROVAL_CHAINS_CONFIGURED",
      category: "config",
      titleEn: "Approval Chains Configured",
      titleAr: "سلاسل الموافقة مُهيأة",
      descriptionEn: "At least one active approval chain configuration must exist.",
      severity: "major",
      status: "pending",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "Will be evaluated when gates are run." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "Configure approval chains in Policy Governance > Approval Chain Configs.",
      remediationAr: "هيّئ سلاسل الموافقة في حوكمة السياسات.",
      sortOrder: 120,
    },
    // UAT category
    {
      gateCode: "PILOT_UAT_COMPLETE",
      category: "uat",
      titleEn: "Pilot UAT Complete (≥5 passed runs)",
      titleAr: "اختبار قبول المستخدم مكتمل (5 جولات ناجحة على الأقل)",
      descriptionEn: "At least 5 UAT test runs must have passed across all roles.",
      severity: "critical",
      status: "fail",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ passedUatRuns: 0, required: 5 }),
      blockerDescriptionEn: "No passed UAT runs found. Complete pilot UAT testing before go-live.",
      blockerDescriptionAr: "لم يتم العثور على جولات UAT ناجحة. أكمل اختبارات UAT قبل الإطلاق.",
      remediationEn: "Execute UAT scripts for all pilot roles. At least 5 runs must pass.",
      remediationAr: "نفّذ نصوص UAT لجميع أدوار الاختبار التجريبي.",
      sortOrder: 130,
    },
    // SECURITY category
    {
      gateCode: "SECURITY_SCAN_RUN",
      category: "security",
      titleEn: "Security Scan Run in Last 30 Days",
      titleAr: "فحص أمني تم في آخر 30 يوماً",
      descriptionEn: "A completed security test run must exist within the last 30 days.",
      severity: "critical",
      status: "fail",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ completedSecurityRunsInLast30Days: 0 }),
      blockerDescriptionEn: "No completed security test run found in the last 30 days. Run security tests before go-live.",
      blockerDescriptionAr: "لا يوجد فحص أمني مكتمل في آخر 30 يوماً.",
      remediationEn: "Run a full security test suite via POST /api/security-test-runs.",
      remediationAr: "قم بتشغيل مجموعة الاختبارات الأمنية الكاملة.",
      sortOrder: 140,
    },
    // MIGRATION category
    {
      gateCode: "MIGRATION_COMPLETE",
      category: "migration",
      titleEn: "All Required Data Migrations Complete",
      titleAr: "جميع عمليات الترحيل المطلوبة مكتملة",
      descriptionEn: "All required data migration items must be in 'complete' status.",
      severity: "critical",
      status: "fail",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "Will be evaluated at gate run time." }),
      blockerDescriptionEn: "Some required data migrations are incomplete. Complete all required migrations before go-live.",
      blockerDescriptionAr: "بعض عمليات الترحيل المطلوبة غير مكتملة.",
      remediationEn: "Complete all required migrations tracked in Migration Status.",
      remediationAr: "أكمل جميع عمليات الترحيل المطلوبة في متتبع حالة الترحيل.",
      sortOrder: 150,
    },
    // AUDIT category
    {
      gateCode: "AUDIT_LOGGING_ACTIVE",
      category: "audit",
      titleEn: "Audit Logging Active",
      titleAr: "سجل المراجعة نشط",
      descriptionEn: "Audit log entries must exist in the last 24 hours, confirming logging is operational.",
      severity: "critical",
      status: "pass",
      evaluationType: "automated",
      evidenceJson: JSON.stringify({ note: "Audit logging is active — entries found in last 24 hours." }),
      blockerDescriptionEn: null,
      blockerDescriptionAr: null,
      remediationEn: "No action required.",
      remediationAr: "لا يلزم اتخاذ أي إجراء.",
      sortOrder: 160,
    },
    // UI/BILINGUAL category
    {
      gateCode: "BILINGUAL_UI_VERIFIED",
      category: "bilingual",
      titleEn: "Bilingual UI Verified (English + Arabic)",
      titleAr: "التحقق من واجهة المستخدم ثنائية اللغة (إنجليزي + عربي)",
      descriptionEn: "A human QA reviewer must confirm all UI strings are properly wrapped in t() helper for both English and Arabic.",
      severity: "major",
      status: "pending",
      evaluationType: "manual",
      evidenceJson: JSON.stringify({ note: "Manual gate — requires QA sign-off. Some payroll column headers may not be wrapped in t() helper." }),
      blockerDescriptionEn: "Bilingual UI verification is a manual gate. QA reviewer must sign off before go-live.",
      blockerDescriptionAr: "التحقق من واجهة المستخدم ثنائية اللغة يتطلب موافقة يدوية من فريق الجودة.",
      remediationEn: "Have QA team review all UI components for proper i18n coverage. Fix any missing t() wrappers.",
      remediationAr: "يجب على فريق ضمان الجودة مراجعة جميع مكونات واجهة المستخدم للتحقق من التغطية الكاملة للغة.",
      sortOrder: 170,
    },
  ];

  for (const gate of gates) {
    await db
      .insert(goLiveGatesTable)
      .values({ ...gate, isOverridden: false })
      .onConflictDoUpdate({
        target: goLiveGatesTable.gateCode,
        set: { ...gate, updatedAt: new Date() },
      });
  }

  console.log(`✓ Seeded ${gates.length} go-live gates`);
}

// ─── READINESS SCORECARDS ──────────────────────────────────────────────────────

async function seedReadinessScorecards() {
  const scorecards = [
    {
      module: "authentication",
      moduleDisplayEn: "Authentication & Identity",
      moduleDisplayAr: "المصادقة والهوية",
      readinessStatus: "blocked",
      totalGates: 2,
      passingGates: 0,
      failingGates: 2,
      overriddenGates: 0,
      readinessScore: "0.00",
      notes: "Both auth gates are failing/warn: no session guards, no Keycloak. Critical blocker.",
    },
    {
      module: "payroll",
      moduleDisplayEn: "Payroll Management",
      moduleDisplayAr: "إدارة الرواتب",
      readinessStatus: "partial",
      totalGates: 2,
      passingGates: 1,
      failingGates: 1,
      overriddenGates: 0,
      readinessScore: "50.00",
      notes: "Salary grades configured. Migration incomplete.",
    },
    {
      module: "leave",
      moduleDisplayEn: "Leave Management",
      moduleDisplayAr: "إدارة الإجازات",
      readinessStatus: "partial",
      totalGates: 2,
      passingGates: 1,
      failingGates: 0,
      overriddenGates: 0,
      readinessScore: "75.00",
      notes: "Leave types and holidays pending evaluation.",
    },
    {
      module: "attendance",
      moduleDisplayEn: "Attendance & Time",
      moduleDisplayAr: "الحضور والوقت",
      readinessStatus: "partial",
      totalGates: 2,
      passingGates: 1,
      failingGates: 1,
      overriddenGates: 0,
      readinessScore: "50.00",
      notes: "Device enrollment pending; attendance migration not started.",
    },
    {
      module: "backup_restore",
      moduleDisplayEn: "Backup & Restore",
      moduleDisplayAr: "النسخ الاحتياطي والاستعادة",
      readinessStatus: "blocked",
      totalGates: 3,
      passingGates: 0,
      failingGates: 2,
      overriddenGates: 0,
      readinessScore: "16.67",
      notes: "No verified backup in 7 days. No restore test in 30 days.",
    },
    {
      module: "security",
      moduleDisplayEn: "Security",
      moduleDisplayAr: "الأمان",
      readinessStatus: "blocked",
      totalGates: 3,
      passingGates: 0,
      failingGates: 3,
      overriddenGates: 0,
      readinessScore: "0.00",
      notes: "No session guards, no Keycloak, no security scan. All 3 security gates failing.",
    },
    {
      module: "bilingual_ui",
      moduleDisplayEn: "Bilingual UI",
      moduleDisplayAr: "واجهة المستخدم ثنائية اللغة",
      readinessStatus: "partial",
      totalGates: 1,
      passingGates: 0,
      failingGates: 0,
      overriddenGates: 0,
      readinessScore: "0.00",
      notes: "Manual gate — pending QA review.",
    },
    {
      module: "licensing",
      moduleDisplayEn: "Licensing",
      moduleDisplayAr: "الترخيص",
      readinessStatus: "not_started",
      totalGates: 1,
      passingGates: 0,
      failingGates: 0,
      overriddenGates: 0,
      readinessScore: "0.00",
      notes: "License gate pending evaluation.",
    },
  ];

  for (const sc of scorecards) {
    await db
      .insert(readinessScorecardTable)
      .values({ ...sc, coveredRolesJson: "[]", lastRecalculatedAt: new Date() })
      .onConflictDoUpdate({
        target: readinessScorecardTable.module,
        set: { ...sc, lastRecalculatedAt: new Date(), updatedAt: new Date() },
      });
  }

  console.log(`✓ Seeded ${scorecards.length} readiness scorecards`);
}

// ─── PILOT DEFECTS ─────────────────────────────────────────────────────────────

async function seedPilotDefects() {
  const defects = [
    {
      defectCode: "DEF-001",
      module: "authentication",
      titleEn: "Session guards not active: all API endpoints accept unauthenticated requests in demo mode",
      titleAr: "حراسات الجلسة غير نشطة: جميع نقاط الـ API تقبل الطلبات غير المصادق عليها",
      descriptionEn: "The Express server has no Passport.js or equivalent session middleware enforcing authentication. Every route including mutating endpoints (POST, PATCH, DELETE) accepts requests without a valid session cookie. This is intentional for demo/pilot but is a critical blocker for production go-live.",
      stepsToReproduce: "1. Send POST /api/leave-requests without any auth cookie.\n2. Observe: server returns 201 (not 401).\n3. Repeat for any mutating endpoint.",
      severity: "critical",
      status: "open",
      isGoLiveBlocker: true,
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sourceTestCode: "SEC_AUTH_BYPASS",
    },
    {
      defectCode: "DEF-002",
      module: "authorization",
      titleEn: "No role-based access enforcement on mutating endpoints",
      titleAr: "لا يوجد تطبيق للتحكم في الوصول المبني على الأدوار",
      descriptionEn: "Mutating API endpoints do not check the actor's role or permissions. Any user (even unauthenticated in demo mode) can perform payroll closes, employee deletions, and other privileged actions. Role-based authorization middleware is missing from all routes.",
      stepsToReproduce: "1. POST /api/payroll-periods/1/close without being logged in as Payroll Admin.\n2. Observe: operation succeeds without role check.",
      severity: "high",
      status: "open",
      isGoLiveBlocker: true,
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sourceTestCode: "SEC_PRIVILEGE_ESCALATION",
    },
    {
      defectCode: "DEF-003",
      module: "ui_bilingual",
      titleEn: "Some payroll column headers not wrapped in t() helper",
      titleAr: "بعض رؤوس أعمدة الرواتب غير ملفوفة في مساعد t()",
      descriptionEn: "Several column headers and labels in the Payroll module (e.g. 'Basic Salary', 'Housing Allowance', 'Net Pay') are hardcoded English strings not wrapped in the t() i18n helper. These will not translate to Arabic for government/ministry users.",
      stepsToReproduce: "1. Switch UI language to Arabic.\n2. Navigate to Payroll > Payslip view.\n3. Observe: some column headers remain in English.",
      severity: "medium",
      status: "open",
      isGoLiveBlocker: false,
      relatedGateCode: "BILINGUAL_UI_VERIFIED",
      sourceTestCode: "UAT-PAY-002",
    },
    {
      defectCode: "DEF-004",
      module: "integration",
      titleEn: "LDAP connection profile in pending_approval state",
      titleAr: "ملف تعريف اتصال LDAP في حالة انتظار الموافقة",
      descriptionEn: "The LDAP integration connection profile was created but not approved through the governance workflow. It remains in 'pending_approval' status, meaning directory synchronization is not active.",
      stepsToReproduce: "1. Navigate to Integration Governance > Connection Profiles.\n2. Observe LDAP profile is in pending_approval status.",
      severity: "low",
      status: "open",
      isGoLiveBlocker: false,
      relatedGateCode: "AUTH_KEYCLOAK_INTEGRATION",
      sourceTestCode: null,
    },
    {
      defectCode: "DEF-005",
      module: "security",
      titleEn: "Keycloak SSO integration not configured",
      titleAr: "تكامل Keycloak SSO غير مُهيأ",
      descriptionEn: "No Keycloak OIDC or SAML integration profile has been created and approved. Enterprise SSO authentication is therefore not available, requiring users to rely on local credentials only (or no auth in demo mode).",
      stepsToReproduce: "1. Navigate to Integration Governance > Connection Profiles.\n2. Filter by integration_type IN (sso_oidc, sso_saml).\n3. Observe: no profiles exist.",
      severity: "high",
      status: "open",
      isGoLiveBlocker: true,
      relatedGateCode: "AUTH_KEYCLOAK_INTEGRATION",
      sourceTestCode: null,
    },
    {
      defectCode: "DEF-006",
      module: "backup_restore",
      titleEn: "No restore test performed in last 30 days",
      titleAr: "لم يتم إجراء اختبار استعادة في آخر 30 يوماً",
      descriptionEn: "The DATA_RESTORE_TESTED gate requires a successful full restore test within the last 30 days. No restore test has been performed in this environment. The restore_test_results table has only a single 'fail' record from the seed.",
      stepsToReproduce: "1. GET /api/restore-tests/latest.\n2. Observe: most recent result is 'fail', no pass within 30 days.",
      severity: "medium",
      status: "open",
      isGoLiveBlocker: false,
      relatedGateCode: "DATA_RESTORE_TESTED",
      sourceTestCode: null,
    },
  ];

  for (const defect of defects) {
    const existing = await db
      .select()
      .from(pilotDefectsTable)
      .where(eq(pilotDefectsTable.defectCode, defect.defectCode));
    if (existing.length === 0) {
      await db.insert(pilotDefectsTable).values({
        ...defect,
        reportedByUserId: 1,
        reportedAt: new Date(),
      });
    }
  }

  console.log(`✓ Seeded ${defects.length} pilot defects`);
}

// ─── MIGRATION STATUS ──────────────────────────────────────────────────────────

async function seedMigrationStatus() {
  const items = [
    {
      migrationCode: "MIG_EMPLOYEES",
      titleEn: "Employee Master Data Migration",
      titleAr: "ترحيل بيانات الموظفين الرئيسية",
      descriptionEn: "Migrate all employee records from legacy HR system including personal details, employment history, and grade assignments.",
      status: "complete",
      priority: "required",
      totalRecords: 150,
      migratedRecords: 150,
      failedRecords: 0,
      progressPercent: "100.00",
      sourceSystem: "Legacy HR System v3.2",
      isGoLiveBlocker: true,
      sortOrder: 10,
    },
    {
      migrationCode: "MIG_LEAVE_BALANCES",
      titleEn: "Leave Balance Migration",
      titleAr: "ترحيل أرصدة الإجازات",
      descriptionEn: "Migrate current year leave balances for all 150 employees including annual, sick, and emergency leave.",
      status: "complete",
      priority: "required",
      totalRecords: 145,
      migratedRecords: 145,
      failedRecords: 0,
      progressPercent: "100.00",
      sourceSystem: "Legacy HR System v3.2",
      isGoLiveBlocker: true,
      sortOrder: 20,
    },
    {
      migrationCode: "MIG_SALARY_GRADES",
      titleEn: "Salary Grade Structure Migration",
      titleAr: "ترحيل هيكل درجات الراتب",
      descriptionEn: "Migrate the complete salary grade structure including all bands, levels, and pay ranges.",
      status: "complete",
      priority: "required",
      totalRecords: 8,
      migratedRecords: 8,
      failedRecords: 0,
      progressPercent: "100.00",
      sourceSystem: "Finance System",
      isGoLiveBlocker: true,
      sortOrder: 30,
    },
    {
      migrationCode: "MIG_PUBLIC_HOLIDAYS",
      titleEn: "Public Holidays Calendar Migration",
      titleAr: "ترحيل تقويم الإجازات الرسمية",
      descriptionEn: "Migrate public holiday calendar data for current and previous years.",
      status: "complete",
      priority: "required",
      totalRecords: 12,
      migratedRecords: 12,
      failedRecords: 0,
      progressPercent: "100.00",
      sourceSystem: "Manual entry / Ministry of HR calendar",
      isGoLiveBlocker: false,
      sortOrder: 40,
    },
    {
      migrationCode: "MIG_ORG_STRUCTURE",
      titleEn: "Organizational Structure Migration",
      titleAr: "ترحيل الهيكل التنظيمي",
      descriptionEn: "Migrate complete departmental hierarchy, org units, and reporting lines.",
      status: "complete",
      priority: "required",
      totalRecords: 12,
      migratedRecords: 12,
      failedRecords: 0,
      progressPercent: "100.00",
      sourceSystem: "Legacy HR System v3.2",
      isGoLiveBlocker: true,
      sortOrder: 50,
    },
    {
      migrationCode: "MIG_HISTORICAL_PAYROLL",
      titleEn: "Historical Payroll Data Migration (36 months)",
      titleAr: "ترحيل بيانات الرواتب التاريخية (36 شهراً)",
      descriptionEn: "Migrate 36 months of historical payroll run data for reporting and audit purposes. Currently 60% complete.",
      status: "in_progress",
      priority: "recommended",
      totalRecords: 5400,
      migratedRecords: 3240,
      failedRecords: 18,
      progressPercent: "60.00",
      sourceSystem: "Legacy Payroll System",
      isGoLiveBlocker: false,
      sortOrder: 60,
    },
    {
      migrationCode: "MIG_HISTORICAL_ATTENDANCE",
      titleEn: "Historical Attendance Records Migration",
      titleAr: "ترحيل سجلات الحضور التاريخية",
      descriptionEn: "Migrate punch event and attendance records from legacy biometric system. BLOCKER: Legacy system export format not yet documented.",
      status: "not_started",
      priority: "required",
      totalRecords: null,
      migratedRecords: 0,
      failedRecords: 0,
      progressPercent: "0.00",
      sourceSystem: "Legacy Biometric System",
      isGoLiveBlocker: true,
      sortOrder: 70,
    },
    {
      migrationCode: "MIG_LEAVE_HISTORY",
      titleEn: "Historical Leave Requests Migration",
      titleAr: "ترحيل سجلات الإجازات التاريخية",
      descriptionEn: "Migrate 3 years of historical leave request records for continuity and audit compliance.",
      status: "not_started",
      priority: "recommended",
      totalRecords: null,
      migratedRecords: 0,
      failedRecords: 0,
      progressPercent: "0.00",
      sourceSystem: "Legacy HR System v3.2",
      isGoLiveBlocker: false,
      sortOrder: 80,
    },
  ];

  for (const item of items) {
    const existing = await db
      .select()
      .from(migrationStatusTable)
      .where(eq(migrationStatusTable.migrationCode, item.migrationCode));
    if (existing.length === 0) {
      await db.insert(migrationStatusTable).values({
        ...item,
        startedAt: item.status !== "not_started" ? new Date("2024-11-01") : null,
        completedAt: item.status === "complete" ? new Date("2024-12-01") : null,
        runByUserId: 1,
      });
    }
  }

  console.log(`✓ Seeded ${items.length} migration status items`);
}

// ─── RESTORE TEST RESULTS ──────────────────────────────────────────────────────

async function seedRestoreTestResults() {
  const existing = await db.select().from(restoreTestResultsTable).limit(1);
  if (existing.length > 0) {
    console.log("✓ Restore test results already seeded");
    return;
  }

  await db.insert(restoreTestResultsTable).values({
    restoreType: "full",
    result: "fail",
    restoreDurationSeconds: null,
    verificationChecksJson: JSON.stringify([
      { check: "employee_table_row_count", status: "not_run" },
      { check: "leave_balances_integrity", status: "not_run" },
      { check: "payroll_data_consistency", status: "not_run" },
    ]),
    rowCountsJson: null,
    failureReason: "Restore test has not been performed in this environment. This record indicates the required restore test is outstanding.",
    testedByUserId: 1,
    testedAt: new Date("2024-10-01"),
    notes: "SEED — restore test not yet performed. Schedule and execute a full restore test before go-live.",
  });

  console.log("✓ Seeded 1 restore test result (fail — not yet tested)");
}

// ─── UAT SCRIPTS ──────────────────────────────────────────────────────────────

function makeSteps(steps: Array<{ action: string; expected: string; navigate?: string; inputData?: string }>): string {
  return JSON.stringify(
    steps.map((s, i) => ({
      stepNumber: i + 1,
      actionEn: s.action,
      actionAr: s.action,
      expectedResultEn: s.expected,
      expectedResultAr: s.expected,
      navigateTo: s.navigate ?? null,
      inputData: s.inputData ?? null,
      screenshotRequired: false,
      isOptional: false,
    }))
  );
}

async function seedUatScripts() {
  const scripts = [
    // ─── HR Admin ────────────────────────────────────────────────────────────
    {
      scriptCode: "UAT-HR-001",
      titleEn: "Employee Lifecycle Management",
      titleAr: "إدارة دورة حياة الموظف",
      targetRole: "hr_admin",
      module: "admin",
      estimatedMinutes: 30,
      prerequisitesEn: "At least one active department and salary grade must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Employees > Add New Employee", expected: "Employee creation form displays", navigate: "/employees/new" },
        { action: "Fill in required fields: name, employee number, hire date, department, salary grade", expected: "All fields accept input without errors", inputData: '{"firstNameEn":"Ahmed","lastNameEn":"Al-Rashid","hireDate":"2024-01-15"}' },
        { action: "Submit the new employee form", expected: "Employee created with status 201, employee ID assigned" },
        { action: "Navigate to the employee's profile", expected: "Employee profile displays correctly with all entered information" },
        { action: "Update the employee's job title via PATCH", expected: "Title updated, audit log entry created" },
        { action: "Verify the update appears in audit log", expected: "Audit log shows 'update' action for this employee" },
        { action: "Soft-delete the test employee", expected: "Employee marked inactive, not shown in active employee list" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Employee can be created with all required fields", "Updates are reflected immediately", "Audit log captures all changes"]),
      relatedGateCodes: "PILOT_UAT_COMPLETE,ORG_CONFIGURED",
    },
    {
      scriptCode: "UAT-HR-002",
      titleEn: "Leave Administration",
      titleAr: "إدارة الإجازات",
      targetRole: "hr_admin",
      module: "leave",
      estimatedMinutes: 25,
      prerequisitesEn: "Active employees and leave types must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Leave > Leave Types", expected: "Leave types list displays correctly", navigate: "/leave/types" },
        { action: "Create a new leave type (Special Leave)", expected: "Leave type created with ID, status 201" },
        { action: "Navigate to Leave > Leave Balances", expected: "Balance management screen displays" },
        { action: "Set annual leave balance for Employee #1 to 20 days", expected: "Balance updated, shows 20 days available" },
        { action: "View Employee #1 leave history", expected: "Leave history displays all requests and balances" },
        { action: "Force-approve a pending leave request as HR Admin override", expected: "Request approved, balance deducted" },
        { action: "Verify balance deduction in Leave Balances", expected: "Used days increased correctly" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Leave types can be created and managed", "Balances are correctly maintained", "HR Admin can override approval decisions"]),
      relatedGateCodes: "LEAVE_TYPES_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-HR-003",
      titleEn: "Payroll Administration",
      titleAr: "إدارة الرواتب",
      targetRole: "hr_admin",
      module: "payroll",
      estimatedMinutes: 35,
      prerequisitesEn: "Active salary grades and at least one payroll period must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Payroll > Salary Grades", expected: "Salary grades list displays", navigate: "/payroll/salary-grades" },
        { action: "Create a new salary grade for Grade 7", expected: "Grade created with min/max salary bands" },
        { action: "Assign Employee #1 to the new salary grade", expected: "Assignment saved, payroll reflects new grade" },
        { action: "Navigate to Payroll > Payroll Periods", expected: "Payroll periods list displays" },
        { action: "Create a new payroll period for current month", expected: "Period created with status 'open'" },
        { action: "Run payroll calculation for the period", expected: "Payroll runs generated for all employees in period" },
        { action: "Review payroll run details for Employee #1", expected: "Pay components breakdown displays correctly" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Salary grades can be created and assigned", "Payroll periods can be managed", "Payroll calculations run without errors"]),
      relatedGateCodes: "PAYROLL_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-HR-004",
      titleEn: "Document Management",
      titleAr: "إدارة الوثائق",
      targetRole: "hr_admin",
      module: "documents",
      estimatedMinutes: 20,
      prerequisitesEn: "Document categories must be configured.",
      stepsJson: makeSteps([
        { action: "Navigate to Documents > Upload Document", expected: "Document upload form displays", navigate: "/documents/upload" },
        { action: "Upload an employment contract PDF for Employee #1", expected: "Document uploaded with metadata, ID assigned" },
        { action: "Verify document appears in Employee #1 documents list", expected: "Document listed with correct category and date" },
        { action: "Download the uploaded document", expected: "Document downloads correctly without corruption" },
        { action: "Update document metadata (add expiry date)", expected: "Metadata updated, audit log entry created" },
        { action: "Archive the document", expected: "Document archived, no longer in active list" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Documents can be uploaded and retrieved", "Metadata can be updated", "Document archiving works correctly"]),
      relatedGateCodes: "PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-HR-005",
      titleEn: "Audit Log Review",
      titleAr: "مراجعة سجل المراجعة",
      targetRole: "hr_admin",
      module: "reporting",
      estimatedMinutes: 15,
      prerequisitesEn: "System must have been in use for at least 24 hours.",
      stepsJson: makeSteps([
        { action: "Navigate to Admin > Audit Logs", expected: "Audit log viewer displays", navigate: "/admin/audit" },
        { action: "Filter audit logs by entity_type = employee", expected: "Only employee-related audit entries shown" },
        { action: "Filter audit logs by last 24 hours", expected: "Recent entries display correctly with actor and timestamp" },
        { action: "Export audit logs to CSV", expected: "CSV file downloads with correct columns and data" },
        { action: "Verify audit entry for a known recent action (e.g., employee update)", expected: "Specific audit entry found with correct actor, action, and entity" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Audit logs are queryable and filterable", "Export functionality works", "All recent actions are properly logged"]),
      relatedGateCodes: "AUDIT_LOGGING_ACTIVE,PILOT_UAT_COMPLETE",
    },
    // ─── Payroll Admin ────────────────────────────────────────────────────────
    {
      scriptCode: "UAT-PAY-001",
      titleEn: "Payroll Calculation Verification",
      titleAr: "التحقق من حساب الرواتب",
      targetRole: "payroll_admin",
      module: "payroll",
      estimatedMinutes: 40,
      prerequisitesEn: "An open payroll period with employee assignments must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Payroll > Run Calculation for current period", expected: "Calculation runs without errors", navigate: "/payroll/run" },
        { action: "Review calculation results for Employee #1", expected: "Base salary, allowances, and deductions shown correctly" },
        { action: "Verify overtime calculation for Employee #2 (with overtime entries)", expected: "Overtime hours × rate = correct overtime pay" },
        { action: "Check that housing allowance is correctly prorated for partial month hire", expected: "Proration formula applied correctly" },
        { action: "Verify net pay = gross pay − deductions", expected: "Net pay calculation matches manual verification" },
        { action: "Generate payroll exception report", expected: "Exceptions list shows anomalies (negative pay, missing grade)" },
        { action: "Review and approve all exceptions", expected: "Exceptions cleared, period ready for approval" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Payroll calculations are accurate", "Overtime is correctly computed", "Proration works for partial months", "Exception handling is functional"]),
      relatedGateCodes: "PAYROLL_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-PAY-002",
      titleEn: "Payslip Generation and Distribution",
      titleAr: "إنشاء وتوزيع قسائم الراتب",
      targetRole: "payroll_admin",
      module: "payroll",
      estimatedMinutes: 25,
      prerequisitesEn: "A finalized payroll period must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Payroll > Payslips", expected: "Payslip management screen displays", navigate: "/payroll/payslips" },
        { action: "Generate payslips for all employees in current period", expected: "Payslips generated as PDF, employee portal updated" },
        { action: "View payslip for Employee #1", expected: "Payslip shows correct breakdown: basic, allowances, deductions, net pay" },
        { action: "Verify bilingual labels (English + Arabic) on payslip", expected: "All column headers display in both languages" },
        { action: "Download individual payslip PDF", expected: "PDF downloads correctly with correct formatting" },
        { action: "Mark payslips as distributed", expected: "Distribution status updated, employees notified" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Payslips generate correctly for all employees", "Bilingual labels display correctly", "PDF export works", "Distribution workflow complete"]),
      relatedGateCodes: "BILINGUAL_UI_VERIFIED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-PAY-003",
      titleEn: "Payroll Period Close Workflow",
      titleAr: "سير عمل إغلاق فترة الرواتب",
      targetRole: "payroll_admin",
      module: "payroll",
      estimatedMinutes: 20,
      prerequisitesEn: "An approved payroll period must be ready to close.",
      stepsJson: makeSteps([
        { action: "Navigate to open payroll period", expected: "Period status shows 'approved' and ready to close", navigate: "/payroll/periods" },
        { action: "Attempt to close already-closed period", expected: "System returns 409 Conflict — duplicate close rejected" },
        { action: "Close the approved period", expected: "Period status changes to 'closed', no further edits allowed" },
        { action: "Verify closed period is read-only", expected: "Edit and delete controls disabled for closed period" },
        { action: "Attempt to create a payroll run for closed period", expected: "System rejects with appropriate error" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Period close is idempotent — duplicate close returns 409", "Closed periods are immutable", "Payroll integrity maintained after close"]),
      relatedGateCodes: "PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-PAY-004",
      titleEn: "Payroll Exception Handling",
      titleAr: "معالجة استثناءات الرواتب",
      targetRole: "payroll_admin",
      module: "payroll",
      estimatedMinutes: 25,
      prerequisitesEn: "Employees with no-show or excused absence records must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Payroll > Exceptions", expected: "Exception list shows employees with issues", navigate: "/payroll/exceptions" },
        { action: "Review employee with unexcused no-show", expected: "Deduction amount calculated and displayed" },
        { action: "Mark no-show as excused for Employee #2", expected: "Deduction reversed, net pay updated" },
        { action: "View updated pay calculation", expected: "Excused absence correctly removes deduction" },
        { action: "Review final exception list", expected: "All exceptions either resolved or explicitly retained" },
        { action: "Export exception report", expected: "Report exports with all decisions documented" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Exceptions are correctly identified", "Excused absences reverse deductions", "Exception reports export correctly"]),
      relatedGateCodes: "PAYROLL_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    // ─── Line Manager ─────────────────────────────────────────────────────────
    {
      scriptCode: "UAT-MGR-001",
      titleEn: "Leave Approval Workflow",
      titleAr: "سير عمل الموافقة على الإجازات",
      targetRole: "line_manager",
      module: "leave",
      estimatedMinutes: 20,
      prerequisitesEn: "Direct reports with pending leave requests must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Approvals > Leave Requests pending my action", expected: "Pending leave requests from direct reports display", navigate: "/approvals/leave" },
        { action: "Review leave request details for Employee #3", expected: "Request details, leave balance, and calendar conflict check display" },
        { action: "Approve the leave request", expected: "Request status changes to 'approved', employee notified" },
        { action: "Verify leave balance deducted for Employee #3", expected: "Available days reduced by approved leave duration" },
        { action: "Review a second leave request and reject with reason", expected: "Request rejected, rejection reason saved, employee notified" },
        { action: "Verify no balance deduction for rejected request", expected: "Employee's balance unchanged after rejection" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Manager can approve and reject leave requests", "Balance updates correctly on approval", "Rejection reason is saved and communicated"]),
      relatedGateCodes: "LEAVE_TYPES_CONFIGURED,APPROVAL_CHAINS_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-MGR-002",
      titleEn: "Attendance Review and Correction",
      titleAr: "مراجعة الحضور والتصحيح",
      targetRole: "line_manager",
      module: "attendance",
      estimatedMinutes: 25,
      prerequisitesEn: "Employees with attendance records and potential anomalies must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Attendance > My Team Overview", expected: "Team attendance summary for current month displays", navigate: "/attendance/team" },
        { action: "Identify employee with missing punch-out", expected: "Attendance anomaly flag shown for the employee" },
        { action: "Submit an attendance correction request for the missing punch-out", expected: "Correction request created, pending approval" },
        { action: "Approve the correction request", expected: "Punch-out corrected, attendance record updated" },
        { action: "Verify corrected attendance in employee's attendance log", expected: "Corrected entry shows with 'corrected' label" },
        { action: "Download attendance report for team", expected: "Report downloads with correct data" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Attendance anomalies are visible", "Corrections can be submitted and approved", "Reports generate correctly"]),
      relatedGateCodes: "DEVICES_ENROLLED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-MGR-003",
      titleEn: "Performance Review Workflow",
      titleAr: "سير عمل تقييم الأداء",
      targetRole: "line_manager",
      module: "performance",
      estimatedMinutes: 30,
      prerequisitesEn: "An active appraisal cycle must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Performance > Appraisal Cycle", expected: "Active appraisal cycle displayed", navigate: "/performance/appraisals" },
        { action: "Start appraisal for direct report Employee #3", expected: "Appraisal form opens with employee competencies" },
        { action: "Score each competency dimension (1–5 scale)", expected: "Scores saved, overall rating calculated" },
        { action: "Add qualitative comments for each dimension", expected: "Comments saved, character limit not exceeded" },
        { action: "Submit final appraisal rating", expected: "Appraisal submitted, status changes to 'manager_submitted'" },
        { action: "Verify appraisal appears in calibration session", expected: "Rating visible in calibration queue" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Appraisals can be submitted for direct reports", "Ratings calculate correctly", "Calibration session receives submitted appraisals"]),
      relatedGateCodes: "PILOT_UAT_COMPLETE",
    },
    // ─── Employee Self-Service ────────────────────────────────────────────────
    {
      scriptCode: "UAT-EMP-001",
      titleEn: "Leave Request Submission",
      titleAr: "تقديم طلب إجازة",
      targetRole: "employee",
      module: "self_service",
      estimatedMinutes: 15,
      prerequisitesEn: "Employee must have leave balance and the request workflow must be configured.",
      stepsJson: makeSteps([
        { action: "Navigate to My Leave > Submit Leave Request", expected: "Leave request form displays with balance information", navigate: "/my/leave/request" },
        { action: "Select Annual Leave type and choose dates for next week", expected: "Calendar highlights selected dates, duration calculated" },
        { action: "Review balance before submission", expected: "Available balance shown, request within balance" },
        { action: "Submit the leave request", expected: "Request submitted with status 'pending', confirmation shown" },
        { action: "View the submitted request in My Leave History", expected: "Request appears with status 'pending' and correct dates" },
        { action: "Attempt to cancel the pending request", expected: "Request cancelled, balance restored (pending → 0)" },
        { action: "Submit a second request for the same dates", expected: "Request accepted since previous was cancelled" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Leave can be submitted and cancelled", "Balance shows correctly before submission", "Cancellation restores balance"]),
      relatedGateCodes: "LEAVE_TYPES_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-EMP-002",
      titleEn: "Payslip View",
      titleAr: "عرض قسيمة الراتب",
      targetRole: "employee",
      module: "self_service",
      estimatedMinutes: 10,
      prerequisitesEn: "Employee must have at least one finalized payslip.",
      stepsJson: makeSteps([
        { action: "Navigate to My Payslips", expected: "List of payslips for current and past periods displays", navigate: "/my/payslips" },
        { action: "Click on the most recent payslip", expected: "Payslip detail view opens with full breakdown" },
        { action: "Verify all pay components are listed (basic, allowances, deductions)", expected: "All components shown with correct amounts" },
        { action: "Verify bilingual display (toggle to Arabic)", expected: "All labels correctly display in Arabic" },
        { action: "Download payslip as PDF", expected: "PDF downloads correctly with correct formatting and amounts" },
        { action: "Verify net pay matches expected calculation", expected: "Net pay = basic + allowances − deductions" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Payslips are accessible to employees", "Full breakdown is visible", "PDF download works", "Arabic translation is correct"]),
      relatedGateCodes: "BILINGUAL_UI_VERIFIED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-EMP-003",
      titleEn: "Employee Profile Update",
      titleAr: "تحديث ملف الموظف",
      targetRole: "employee",
      module: "self_service",
      estimatedMinutes: 15,
      prerequisitesEn: "Employee must be able to access their own profile.",
      stepsJson: makeSteps([
        { action: "Navigate to My Profile", expected: "Profile page shows current employee information", navigate: "/my/profile" },
        { action: "Update personal contact number", expected: "Field accepts input, save button active" },
        { action: "Submit profile update", expected: "Update saved, confirmation message shown" },
        { action: "Verify change reflected immediately in profile", expected: "New contact number shows in profile" },
        { action: "Attempt to update salary grade (restricted field)", expected: "Salary grade field is read-only for employees" },
        { action: "Submit a self-service request for name change", expected: "Request submitted for HR review, not auto-applied" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Employees can update allowed fields", "Restricted fields are read-only", "Change requests go through approval"]),
      relatedGateCodes: "PILOT_UAT_COMPLETE",
    },
    // ─── Attendance Supervisor ────────────────────────────────────────────────
    {
      scriptCode: "UAT-ATT-001",
      titleEn: "Punch Event Review",
      titleAr: "مراجعة أحداث البصمة",
      targetRole: "attendance_supervisor",
      module: "attendance",
      estimatedMinutes: 20,
      prerequisitesEn: "Active attendance devices must be enrolled with recent punch data.",
      stepsJson: makeSteps([
        { action: "Navigate to Attendance > Punch Events", expected: "Recent punch events list displays with device info", navigate: "/attendance/punch-events" },
        { action: "Filter events by date range (last 7 days)", expected: "Filtered results show only events within range" },
        { action: "Identify duplicate punch event from same employee within 1 minute", expected: "Duplicate flagged or filtered in view" },
        { action: "Review raw punch data for Device #1", expected: "Device-level punch events display correctly" },
        { action: "Mark a suspicious punch event for review", expected: "Event flagged, supervisor note saved" },
        { action: "Generate daily attendance report", expected: "Report shows all in/out times with duration" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Punch events are visible and filterable", "Duplicates can be identified", "Reports generate correctly"]),
      relatedGateCodes: "DEVICES_ENROLLED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-ATT-002",
      titleEn: "Attendance Correction Workflow",
      titleAr: "سير عمل تصحيح الحضور",
      targetRole: "attendance_supervisor",
      module: "attendance",
      estimatedMinutes: 20,
      prerequisitesEn: "Employees with missing punch records must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Attendance > Corrections", expected: "Correction requests list displays", navigate: "/attendance/corrections" },
        { action: "Submit a new correction for Employee #2 (missing check-out at 17:30)", expected: "Correction request created with supporting reason" },
        { action: "Review and approve the correction", expected: "Correction applied, attendance record updated" },
        { action: "Verify corrected record in daily attendance view", expected: "Corrected punch shows with supervisor annotation" },
        { action: "Reject a correction request with insufficient evidence", expected: "Rejection saved with reason, employee notified" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Corrections can be submitted and processed", "Approval workflow functions", "Rejected corrections include reason"]),
      relatedGateCodes: "DEVICES_ENROLLED,APPROVAL_CHAINS_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-ATT-003",
      titleEn: "Device Health Monitoring",
      titleAr: "مراقبة صحة الأجهزة",
      targetRole: "attendance_supervisor",
      module: "attendance",
      estimatedMinutes: 15,
      prerequisitesEn: "At least one active attendance device must be enrolled.",
      stepsJson: makeSteps([
        { action: "Navigate to Attendance > Devices", expected: "Device list displays with status indicators", navigate: "/attendance/devices" },
        { action: "Check device last sync time for Device #1", expected: "Last sync timestamp shows, should be within last hour" },
        { action: "View device mapping configuration", expected: "Device-to-department/branch mappings display correctly" },
        { action: "Check for any device alerts", expected: "Alerts section shows device connectivity status" },
        { action: "Simulate device offline by checking sync health", expected: "Health status reflects current device connectivity" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Device health is visible", "Sync status is current", "Alerts are displayed"]),
      relatedGateCodes: "DEVICES_ENROLLED,PILOT_UAT_COMPLETE",
    },
    // ─── Auditor ──────────────────────────────────────────────────────────────
    {
      scriptCode: "UAT-AUD-001",
      titleEn: "Audit Log Review and Export",
      titleAr: "مراجعة سجل المراجعة وتصديره",
      targetRole: "auditor",
      module: "reporting",
      estimatedMinutes: 20,
      prerequisitesEn: "System must have audit log entries across multiple entity types.",
      stepsJson: makeSteps([
        { action: "Navigate to Audit > Audit Logs", expected: "Full audit log viewer displays", navigate: "/audit" },
        { action: "Filter by actor_user_id = 1 and last 7 days", expected: "Logs filtered to show only system admin actions" },
        { action: "Filter by action = create and entity_type = employee", expected: "Only employee creation events shown" },
        { action: "Verify log entries are immutable (no edit button)", expected: "Audit log entries have no edit or delete controls" },
        { action: "Export audit logs for last 30 days as CSV", expected: "CSV exports with all required fields" },
        { action: "Verify export contains required fields (actor, action, entity, timestamp)", expected: "All four required fields present in export" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Audit logs are queryable", "Logs are immutable", "Export works with required fields"]),
      relatedGateCodes: "AUDIT_LOGGING_ACTIVE,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-AUD-002",
      titleEn: "Dual-Authorization Review",
      titleAr: "مراجعة التفويض المزدوج",
      targetRole: "auditor",
      module: "admin",
      estimatedMinutes: 15,
      prerequisitesEn: "Dual-auth requests must exist in the system.",
      stepsJson: makeSteps([
        { action: "Navigate to Admin > Dual Authorization Requests", expected: "Dual-auth request queue displays", navigate: "/admin/dual-auth" },
        { action: "Review a completed dual-auth request", expected: "Both approver IDs, timestamps, and justification visible" },
        { action: "Verify dual-auth was used for a sensitive operation (e.g., payroll close)", expected: "Audit trail shows two distinct approvers" },
        { action: "Search for any dual-auth requests that bypassed second approver", expected: "No bypass records found — all have two approvals" },
        { action: "Export dual-auth report", expected: "Report exports with all dual-auth events" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Dual-auth history is visible and auditable", "No bypass events exist", "Report exports correctly"]),
      relatedGateCodes: "AUDIT_LOGGING_ACTIVE,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-AUD-003",
      titleEn: "Break-Glass Access Review",
      titleAr: "مراجعة الوصول الطارئ",
      targetRole: "auditor",
      module: "security",
      estimatedMinutes: 15,
      prerequisitesEn: "At least one break-glass access event must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Admin > Break-Glass Access Log", expected: "Break-glass access history displays", navigate: "/admin/break-glass" },
        { action: "Review most recent break-glass entry", expected: "Entry shows: actor, justification, scope, timestamp, duration" },
        { action: "Verify break-glass access has audit log entry", expected: "Corresponding audit_logs entry found" },
        { action: "Check no break-glass session exceeded authorized duration", expected: "All sessions within authorized time window" },
        { action: "Export break-glass audit report", expected: "Report exports with complete chain of custody" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Break-glass access is auditable", "All sessions have complete records", "Report export works"]),
      relatedGateCodes: "AUDIT_LOGGING_ACTIVE,PILOT_UAT_COMPLETE",
    },
    // ─── Security Admin ───────────────────────────────────────────────────────
    {
      scriptCode: "UAT-SEC-001",
      titleEn: "User Access Review",
      titleAr: "مراجعة صلاحيات المستخدمين",
      targetRole: "security_admin",
      module: "security",
      estimatedMinutes: 20,
      prerequisitesEn: "Multiple users with different roles must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Admin > Users", expected: "User list displays with role assignments", navigate: "/admin/users" },
        { action: "Review each user's role and permissions", expected: "Roles are clearly documented and justified" },
        { action: "Identify any users with overly broad permissions", expected: "Flag users with permissions beyond their job function" },
        { action: "Review users who have not logged in for 30+ days", expected: "Inactive users identified for review/deactivation" },
        { action: "Export user access report", expected: "Report shows all users with roles and last login" },
        { action: "Deactivate a test user account", expected: "Account deactivated, user cannot log in" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["User access is reviewable", "Inactive users can be identified", "Accounts can be deactivated"]),
      relatedGateCodes: "AUTH_SESSION_GUARDS,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-SEC-002",
      titleEn: "Security Clearance Management",
      titleAr: "إدارة التصاريح الأمنية",
      targetRole: "security_admin",
      module: "security",
      estimatedMinutes: 20,
      prerequisitesEn: "Employees with security clearance records must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Security > Security Clearances", expected: "Clearance records list displays", navigate: "/security/clearances" },
        { action: "Review Employee #1 security clearance level", expected: "Clearance level, granted date, and expiry display" },
        { action: "Update clearance level for Employee #2", expected: "Clearance updated, audit log entry created" },
        { action: "Check for expired clearances", expected: "Expired clearances highlighted, action required" },
        { action: "Generate clearance expiry report for next 90 days", expected: "Report shows upcoming expirations" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Clearances are manageable", "Expiry tracking works", "Reports generate correctly"]),
      relatedGateCodes: "PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-SEC-003",
      titleEn: "Break-Glass Configuration",
      titleAr: "تهيئة الوصول الطارئ",
      targetRole: "security_admin",
      module: "security",
      estimatedMinutes: 20,
      prerequisitesEn: "Break-glass module must be configured.",
      stepsJson: makeSteps([
        { action: "Navigate to Admin > Break-Glass Configuration", expected: "Break-glass settings display", navigate: "/admin/break-glass" },
        { action: "Review authorized approvers for break-glass access", expected: "Approver list shows designated security officers" },
        { action: "Test break-glass activation with valid justification", expected: "Break-glass session granted, timer starts" },
        { action: "Verify audit log entry created for activation", expected: "Audit entry shows actor, justification, scope, and timestamp" },
        { action: "Verify break-glass session auto-expires after configured duration", expected: "Session expires, further access denied" },
        { action: "Review break-glass audit trail completeness", expected: "Full chain of custody from request to expiry recorded" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Break-glass can be configured", "Activation is audited", "Sessions auto-expire", "Full audit trail exists"]),
      relatedGateCodes: "AUDIT_LOGGING_ACTIVE,PILOT_UAT_COMPLETE",
    },
    // ─── Government User ──────────────────────────────────────────────────────
    {
      scriptCode: "UAT-GOV-001",
      titleEn: "Ministry Leave Workflow",
      titleAr: "سير عمل إجازات الوزارة",
      targetRole: "government_user",
      module: "leave",
      orgTypeApplicability: "government",
      estimatedMinutes: 25,
      prerequisitesEn: "Government organization type must be configured. At least one employee in ministry.",
      stepsJson: makeSteps([
        { action: "Log in as Government HR Manager", expected: "Dashboard shows ministry-specific leave types and policies" },
        { action: "Navigate to Leave > Leave Types — verify government-specific types exist", expected: "Military leave, Hajj leave, and emergency family leave types visible" },
        { action: "Submit a Hajj leave request for Employee #1", expected: "Request created with Hajj leave type, correct duration" },
        { action: "Route request through ministry approval chain", expected: "Request follows configured ministry approval workflow" },
        { action: "Approve request at ministry level", expected: "Final approval granted, leave confirmed" },
        { action: "Generate ministry leave utilization report", expected: "Report shows leave breakdown by leave type for ministry" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Government leave types work correctly", "Ministry approval workflow functions", "Reports are ministry-specific"]),
      relatedGateCodes: "LEAVE_TYPES_CONFIGURED,APPROVAL_CHAINS_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-GOV-002",
      titleEn: "Grade Structure Review (Government)",
      titleAr: "مراجعة هيكل الدرجات (حكومي)",
      targetRole: "government_user",
      module: "payroll",
      orgTypeApplicability: "government",
      estimatedMinutes: 20,
      prerequisitesEn: "Government salary grade structure must be configured.",
      stepsJson: makeSteps([
        { action: "Navigate to Payroll > Salary Grades", expected: "Government grade structure (Grade 1–15) displays", navigate: "/payroll/salary-grades" },
        { action: "Verify government grades follow official salary scale", expected: "Min/max pay ranges match official civil service scale" },
        { action: "Check Employee #1 grade assignment matches payslip", expected: "Grade on profile matches grade used in payroll" },
        { action: "Review grade history for Employee #2 (promoted last year)", expected: "Grade promotion history shows effective dates" },
        { action: "Verify allowances are correctly assigned per grade level", expected: "Housing, transport, and family allowances correct per grade" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Government grade structure is correctly configured", "Allowances are grade-appropriate", "Grade history is tracked"]),
      relatedGateCodes: "PAYROLL_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    // ─── Defense User ─────────────────────────────────────────────────────────
    {
      scriptCode: "UAT-DEF-001",
      titleEn: "Military Rank and Command Review",
      titleAr: "مراجعة الرتبة العسكرية والقيادة",
      targetRole: "defense_user",
      module: "admin",
      orgTypeApplicability: "defense",
      estimatedMinutes: 30,
      prerequisitesEn: "Defense organization type must be configured. Military ranks must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Military > Ranks", expected: "Military rank hierarchy displays (Private through General)", navigate: "/military/ranks" },
        { action: "Verify rank structure is complete and correctly ordered", expected: "All ranks in correct seniority order" },
        { action: "Navigate to Chain of Command", expected: "Command structure visualizer displays", navigate: "/chain-of-command" },
        { action: "Verify reporting chain for a field unit officer", expected: "Chain shows correct reporting line up to command" },
        { action: "Review a mobilization status record", expected: "Deployment status, unit, and dates display correctly" },
        { action: "Verify duty station assignment for Employee #4", expected: "Duty station, posting dates, and assignment reason correct" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Military ranks are correctly structured", "Chain of command is verifiable", "Duty station assignments work"]),
      relatedGateCodes: "ORG_CONFIGURED,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-DEF-002",
      titleEn: "Security Classification Review",
      titleAr: "مراجعة التصنيف الأمني",
      targetRole: "defense_user",
      module: "security",
      orgTypeApplicability: "defense",
      estimatedMinutes: 20,
      prerequisitesEn: "Security clearance records for defense personnel must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Security > Clearances for defense personnel", expected: "Defense personnel clearances display by classification level", navigate: "/security/clearances" },
        { action: "Verify classification levels are correctly set (Confidential, Secret, Top Secret)", expected: "All classification levels properly categorized" },
        { action: "Review access controls for classified information", expected: "Access restricted to clearance-appropriate levels" },
        { action: "Check audit trail for classified data access attempts", expected: "All access attempts logged with user and timestamp" },
        { action: "Export security classification report", expected: "Report exports with all personnel and their clearance levels" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Security classifications are correctly assigned", "Access controls function correctly", "All access is audited"]),
      relatedGateCodes: "AUDIT_LOGGING_ACTIVE,PILOT_UAT_COMPLETE",
    },
    {
      scriptCode: "UAT-DEF-003",
      titleEn: "Mobilization Status Management",
      titleAr: "إدارة حالة التعبئة",
      targetRole: "defense_user",
      module: "admin",
      orgTypeApplicability: "defense",
      estimatedMinutes: 20,
      prerequisitesEn: "Defense personnel with mobilization records must exist.",
      stepsJson: makeSteps([
        { action: "Navigate to Military > Mobilization Status", expected: "Active and historical mobilization records display", navigate: "/military/mobilization" },
        { action: "Review current mobilization status for a unit", expected: "Deployed/standby/inactive status shows for each member" },
        { action: "Update mobilization status for Employee #5 (deployed → returned)", expected: "Status updated, effective date recorded" },
        { action: "Verify payroll adjustment for mobilization allowances", expected: "Deployment allowances correctly added/removed per status" },
        { action: "Generate mobilization report by unit", expected: "Report shows all unit members with current status" },
        { action: "Verify audit log for mobilization status change", expected: "Audit entry records change with actor and timestamp" },
      ]),
      acceptanceCriteriaJson: JSON.stringify(["Mobilization status can be managed", "Payroll adjusts for mobilization", "Reports and audit trail work"]),
      relatedGateCodes: "AUDIT_LOGGING_ACTIVE,PAYROLL_CONFIGURED,PILOT_UAT_COMPLETE",
    },
  ];

  for (const script of scripts) {
    const existing = await db
      .select()
      .from(uatScriptsTable)
      .where(eq(uatScriptsTable.scriptCode, script.scriptCode));
    if (existing.length === 0) {
      await db.insert(uatScriptsTable).values({
        ...script,
        isActive: true,
        version: "1.0",
        acceptanceCriteriaJson: script.acceptanceCriteriaJson,
        createdByUserId: 1,
        orgTypeApplicability: script.orgTypeApplicability ?? "all",
      });
    }
  }

  console.log(`✓ Seeded ${scripts.length} UAT scripts`);
}

// ─── SECURITY TEST SCENARIOS ───────────────────────────────────────────────────

async function seedSecurityTestScenarios() {
  const scenarios = [
    {
      scenarioCode: "TAMPERED_PACKAGE",
      attackVector: "tampered_package",
      titleEn: "Tampered Config Package Import",
      titleAr: "استيراد حزمة تكوين مزوّرة",
      descriptionEn: "Attempt to import a configuration package with an invalid HMAC signature. System must reject the package.",
      severity: "high",
      strideCategory: "Tampering",
      targetEndpoint: "/api/config-packages/import",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ packageJson: { signature: "invalid", payloadChecksum: "invalid", payloadJson: "[]" } }),
      expectedBehaviorEn: "System returns 400 or 422 rejecting the tampered package.",
      expectedStatusCode: 400,
      requiresAuditLog: true,
      requiresSecurityAlert: false,
      executionType: "automated",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 10,
    },
    {
      scenarioCode: "DUPLICATE_PAYROLL_CLOSE",
      attackVector: "duplicate_payroll",
      titleEn: "Duplicate Payroll Period Close",
      titleAr: "إغلاق فترة الرواتب المكرر",
      descriptionEn: "Attempt to close an already-closed payroll period. System must return 409 Conflict.",
      severity: "high",
      strideCategory: "Tampering",
      targetEndpoint: "/api/payroll-periods/:id/close",
      targetMethod: "POST",
      requestTemplateJson: null,
      expectedBehaviorEn: "System returns 409 Conflict for duplicate close on already-closed period.",
      expectedStatusCode: 409,
      requiresAuditLog: true,
      requiresSecurityAlert: false,
      executionType: "automated",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 20,
    },
    {
      scenarioCode: "REPLAY_ATTENDANCE",
      attackVector: "replay_attack",
      titleEn: "Attendance Punch Event Replay Attack",
      titleAr: "هجوم إعادة تشغيل أحداث الحضور",
      descriptionEn: "Submit identical punch events twice (same deviceId, employeeId, eventTime). System should detect and reject duplicates.",
      severity: "medium",
      strideCategory: "Spoofing",
      targetEndpoint: "/api/punch-events",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ deviceId: 1, employeeId: 1, eventType: "check_in", eventTime: "2024-01-15T08:00:00Z" }),
      expectedBehaviorEn: "Second submission returns 409 Conflict.",
      expectedStatusCode: 409,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "automated",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 30,
    },
    {
      scenarioCode: "BREAK_GLASS_AUDIT",
      attackVector: "break_glass_abuse",
      titleEn: "Break-Glass Access Audit Trail Verification",
      titleAr: "التحقق من مسار مراجعة الوصول الطارئ",
      descriptionEn: "Trigger break-glass access and verify that audit_logs contains a corresponding entry.",
      severity: "critical",
      strideCategory: "Repudiation",
      targetEndpoint: "/api/break-glass",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ justification: "SECURITY_TEST", targetUserId: 1 }),
      expectedBehaviorEn: "Break-glass activation creates audit log entry with actor, justification, and timestamp.",
      expectedStatusCode: 201,
      requiresAuditLog: true,
      requiresSecurityAlert: true,
      executionType: "automated",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 40,
    },
    {
      scenarioCode: "MISSING_AUTH_PRIVILEGE_ESCALATION",
      attackVector: "privilege_escalation",
      titleEn: "Unauthenticated Admin Endpoint Access",
      titleAr: "الوصول غير المصادق إلى نقطة نهاية المسؤول",
      descriptionEn: "POST to /api/admin/license without authentication. In demo mode: returns 200 (warn). With session guards: should return 401/403.",
      severity: "critical",
      strideCategory: "Elevation of Privilege",
      targetEndpoint: "/api/admin/license",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ licenseKey: "TEST_KEY" }),
      expectedBehaviorEn: "DEMO MODE: returns 200 (documented gap). Production: should return 401/403.",
      expectedStatusCode: 401,
      requiresAuditLog: true,
      requiresSecurityAlert: true,
      executionType: "automated",
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sortOrder: 50,
    },
    {
      scenarioCode: "MISSING_AUTH_EXPORT",
      attackVector: "unauthorized_export",
      titleEn: "Unauthenticated Data Export Access",
      titleAr: "الوصول غير المصادق لتصدير البيانات",
      descriptionEn: "GET export-jobs endpoint without authentication. DEMO MODE: accessible (warn). Production: should require auth.",
      severity: "high",
      strideCategory: "Information Disclosure",
      targetEndpoint: "/api/export-jobs",
      targetMethod: "GET",
      requestTemplateJson: null,
      expectedBehaviorEn: "DEMO MODE: returns 200 (documented gap). Production: should return 401.",
      expectedStatusCode: 401,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "automated",
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sortOrder: 60,
    },
    {
      scenarioCode: "MASS_ASSIGNMENT",
      attackVector: "mass_assignment",
      titleEn: "Mass Assignment Attack via Extra Fields",
      titleAr: "هجوم التعيين الجماعي عبر حقول إضافية",
      descriptionEn: "POST to employees endpoint with extra privileged fields (isAdmin, roleId, systemRole). Verify extra fields are silently ignored.",
      severity: "medium",
      strideCategory: "Tampering",
      targetEndpoint: "/api/employees",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ firstNameEn: "Test", isAdmin: true, roleId: 999, systemRole: "superadmin" }),
      expectedBehaviorEn: "Extra fields are ignored by Drizzle ORM schema mapping. No 500 error.",
      expectedStatusCode: 400,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "automated",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 70,
    },
    {
      scenarioCode: "SESSION_FIXATION",
      attackVector: "session_fixation",
      titleEn: "Session Fixation Attack",
      titleAr: "هجوم تثبيت الجلسة",
      descriptionEn: "Attempt to use a fixed/stolen session token to access protected endpoints.",
      severity: "critical",
      strideCategory: "Spoofing",
      targetEndpoint: "/api/employees",
      targetMethod: "GET",
      requestTemplateJson: null,
      expectedBehaviorEn: "DEMO MODE: session validation not enforced (manual gate). Production: fixed sessions must be invalidated.",
      expectedStatusCode: 401,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sortOrder: 80,
    },
    {
      scenarioCode: "CROSS_ORG_ACCESS",
      attackVector: "cross_org_access",
      titleEn: "Cross-Organization Data Leakage",
      titleAr: "تسرب البيانات بين المنظمات",
      descriptionEn: "Attempt to access records from Org B while authenticated as a user from Org A.",
      severity: "critical",
      strideCategory: "Information Disclosure",
      targetEndpoint: "/api/employees",
      targetMethod: "GET",
      requestTemplateJson: null,
      expectedBehaviorEn: "DEMO MODE: org isolation not enforced (documented gap). Production: strict org-scoped filtering required.",
      expectedStatusCode: 403,
      requiresAuditLog: true,
      requiresSecurityAlert: true,
      executionType: "manual",
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sortOrder: 90,
    },
    {
      scenarioCode: "FAILED_SYNC",
      attackVector: "failed_sync",
      titleEn: "Attendance Device Sync Failure Behavior",
      titleAr: "سلوك فشل مزامنة جهاز الحضور",
      descriptionEn: "Verify system behavior when an attendance device sync fails mid-way. Data should not be partially committed.",
      severity: "medium",
      strideCategory: "Denial of Service",
      targetEndpoint: "/api/devices",
      targetMethod: "POST",
      requestTemplateJson: null,
      expectedBehaviorEn: "Partial sync data is rolled back or clearly marked as incomplete. No silent partial commits.",
      expectedStatusCode: 500,
      requiresAuditLog: true,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "DEVICES_ENROLLED",
      sortOrder: 100,
    },
    // Additional scenarios
    {
      scenarioCode: "SQL_INJECTION_FILTER",
      attackVector: "api_bypass",
      titleEn: "SQL Injection via Query Parameters",
      titleAr: "حقن SQL عبر معاملات الاستعلام",
      descriptionEn: "Attempt SQL injection via filter parameters (e.g., module='; DROP TABLE employees;--). Drizzle ORM should parameterize queries.",
      severity: "critical",
      strideCategory: "Tampering",
      targetEndpoint: "/api/employees?department=1%27+OR+%271%27%3D%271",
      targetMethod: "GET",
      requestTemplateJson: null,
      expectedBehaviorEn: "Query executes safely with no SQL injection. Returns normal results or empty array.",
      expectedStatusCode: 200,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 110,
    },
    {
      scenarioCode: "NEGATIVE_LEAVE_BALANCE",
      attackVector: "duplicate_payroll",
      titleEn: "Leave Request Exceeding Balance",
      titleAr: "طلب إجازة يتجاوز الرصيد",
      descriptionEn: "Submit a leave request that exceeds available balance. System should reject with clear error.",
      severity: "medium",
      strideCategory: "Tampering",
      targetEndpoint: "/api/leave-requests",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ leaveTypeId: 1, startDate: "2024-01-01", endDate: "2024-12-31", totalDays: 999 }),
      expectedBehaviorEn: "System returns 422 or 400 — insufficient balance.",
      expectedStatusCode: 422,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "LEAVE_TYPES_CONFIGURED",
      sortOrder: 120,
    },
    {
      scenarioCode: "BREAK_GLASS_WITHOUT_JUSTIFICATION",
      attackVector: "break_glass_abuse",
      titleEn: "Break-Glass Without Justification",
      titleAr: "الوصول الطارئ بدون مبرر",
      descriptionEn: "Attempt to activate break-glass access without providing a justification. System should reject.",
      severity: "high",
      strideCategory: "Elevation of Privilege",
      targetEndpoint: "/api/break-glass",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ targetUserId: 1 }),
      expectedBehaviorEn: "System returns 400 — justification is required for break-glass activation.",
      expectedStatusCode: 400,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 130,
    },
    {
      scenarioCode: "PASSWORD_RESET_FLOOD",
      attackVector: "api_bypass",
      titleEn: "Password Reset Rate Limiting",
      titleAr: "تحديد معدل إعادة تعيين كلمة المرور",
      descriptionEn: "Submit multiple password reset requests in rapid succession. System should rate-limit to prevent abuse.",
      severity: "medium",
      strideCategory: "Denial of Service",
      targetEndpoint: "/api/auth/forgot-password",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ email: "test@example.com" }),
      expectedBehaviorEn: "After N requests, system returns 429 Too Many Requests.",
      expectedStatusCode: 429,
      requiresAuditLog: true,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sortOrder: 140,
    },
    {
      scenarioCode: "INSECURE_DIRECT_OBJECT_REF",
      attackVector: "privilege_escalation",
      titleEn: "Insecure Direct Object Reference (IDOR)",
      titleAr: "مرجع كائن مباشر غير آمن",
      descriptionEn: "Access another employee's payslip by manipulating the ID in the URL (e.g., /api/payroll-runs/999 for an employee you don't manage).",
      severity: "high",
      strideCategory: "Information Disclosure",
      targetEndpoint: "/api/payroll-runs/:id",
      targetMethod: "GET",
      requestTemplateJson: null,
      expectedBehaviorEn: "DEMO MODE: returns data (documented gap). Production: should check employee ownership.",
      expectedStatusCode: 403,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sortOrder: 150,
    },
    {
      scenarioCode: "LARGE_PAYLOAD_DOS",
      attackVector: "api_bypass",
      titleEn: "Large Payload Denial of Service",
      titleAr: "رفض الخدمة بحمولة كبيرة",
      descriptionEn: "Send an extremely large JSON payload to crash the server or cause memory exhaustion.",
      severity: "medium",
      strideCategory: "Denial of Service",
      targetEndpoint: "/api/employees",
      targetMethod: "POST",
      requestTemplateJson: null,
      expectedBehaviorEn: "Server returns 413 Payload Too Large and handles gracefully without crash.",
      expectedStatusCode: 413,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 160,
    },
    {
      scenarioCode: "XSS_IN_EMPLOYEE_FIELDS",
      attackVector: "mass_assignment",
      titleEn: "XSS via Employee Name Fields",
      titleAr: "هجوم XSS عبر حقول اسم الموظف",
      descriptionEn: "Submit script tags in employee name fields. API should sanitize or return plaintext; frontend must not execute injected scripts.",
      severity: "high",
      strideCategory: "Tampering",
      targetEndpoint: "/api/employees",
      targetMethod: "POST",
      requestTemplateJson: JSON.stringify({ firstNameEn: "<script>alert('xss')</script>", lastNameEn: "Test" }),
      expectedBehaviorEn: "Data stored as-is (API layer) but UI must escape on render. No script execution.",
      expectedStatusCode: 201,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 170,
    },
    {
      scenarioCode: "TOKEN_EXPIRY_ENFORCEMENT",
      attackVector: "session_fixation",
      titleEn: "Expired JWT/Session Token Enforcement",
      titleAr: "تطبيق انتهاء صلاحية الرمز المميز",
      descriptionEn: "Use an expired JWT token. System should return 401 and not process the request.",
      severity: "critical",
      strideCategory: "Spoofing",
      targetEndpoint: "/api/employees",
      targetMethod: "GET",
      requestTemplateJson: null,
      expectedBehaviorEn: "DEMO MODE: no token validation (documented gap). Production: expired tokens return 401.",
      expectedStatusCode: 401,
      requiresAuditLog: false,
      requiresSecurityAlert: false,
      executionType: "manual",
      relatedGateCode: "AUTH_SESSION_GUARDS",
      sortOrder: 180,
    },
    {
      scenarioCode: "PAYROLL_OVERRIDE_WITHOUT_DUAL_AUTH",
      attackVector: "privilege_escalation",
      titleEn: "Payroll Override Without Dual Authorization",
      titleAr: "تجاوز الرواتب بدون تفويض مزدوج",
      descriptionEn: "Attempt to override a finalized payroll run without going through dual-authorization workflow.",
      severity: "critical",
      strideCategory: "Elevation of Privilege",
      targetEndpoint: "/api/payroll-runs/:id",
      targetMethod: "PATCH",
      requestTemplateJson: JSON.stringify({ baseSalary: "99999" }),
      expectedBehaviorEn: "Override requires dual-auth approval. Direct PATCH on finalized run should be rejected.",
      expectedStatusCode: 403,
      requiresAuditLog: true,
      requiresSecurityAlert: true,
      executionType: "manual",
      relatedGateCode: "SECURITY_SCAN_RUN",
      sortOrder: 190,
    },
    {
      scenarioCode: "AUDIT_LOG_TAMPERING",
      attackVector: "api_bypass",
      titleEn: "Audit Log Tampering Attempt",
      titleAr: "محاولة التلاعب بسجل المراجعة",
      descriptionEn: "Attempt to delete or modify audit log entries via API. System should reject all such attempts.",
      severity: "critical",
      strideCategory: "Repudiation",
      targetEndpoint: "/api/audit-logs",
      targetMethod: "DELETE",
      requestTemplateJson: null,
      expectedBehaviorEn: "No DELETE endpoint exists for audit logs. System returns 404 or 405.",
      expectedStatusCode: 405,
      requiresAuditLog: false,
      requiresSecurityAlert: true,
      executionType: "manual",
      relatedGateCode: "AUDIT_LOGGING_ACTIVE",
      sortOrder: 200,
    },
  ];

  for (const scenario of scenarios) {
    const existing = await db
      .select()
      .from(securityTestScenariosTable)
      .where(eq(securityTestScenariosTable.scenarioCode, scenario.scenarioCode));
    if (existing.length === 0) {
      await db.insert(securityTestScenariosTable).values({
        ...scenario,
        isActive: true,
      });
    }
  }

  console.log(`✓ Seeded ${scenarios.length} security test scenarios`);
}

// ─── SECURITY TEST RUN WITH FINDINGS ──────────────────────────────────────────

async function seedSecurityTestRun() {
  const existingRuns = await db.select().from(securityTestRunsTable).limit(1);
  if (existingRuns.length > 0) {
    console.log("✓ Security test runs already seeded");
    return;
  }

  const scenarios = await db.select().from(securityTestScenariosTable);

  const [run] = await db
    .insert(securityTestRunsTable)
    .values({
      runLabel: "Phase 10 Initial Security Assessment — Demo Environment",
      runType: "mixed",
      status: "complete",
      totalScenarios: scenarios.length,
      passedScenarios: 2,
      failedScenarios: 0,
      skippedScenarios: scenarios.filter(s => s.executionType === "manual").length,
      overallPosture: "at_risk",
      triggeredByUserId: 1,
      startedAt: new Date("2024-12-01T09:00:00Z"),
      completedAt: new Date("2024-12-01T09:45:00Z"),
      summaryJson: JSON.stringify({
        demoMode: true,
        note: "DEMO MODE — auth-related findings are 'warn' not 'fail'. Real session guards would change these results.",
        passed: 2,
        failed: 0,
        warns: 5,
        skipped: scenarios.filter(s => s.executionType === "manual").length,
        criticalBlockers: 0,
        keyFindings: [
          "PASS: Tampered config packages are correctly rejected (signature validation works)",
          "PASS: Duplicate payroll close correctly returns 409 (if closed periods exist)",
          "WARN: Auth endpoints accessible without session — DEMO MODE documented gap",
          "WARN: Replay attack detection partial — no unique constraint on punch events",
          "WARN: Privilege escalation possible — no role checks on admin endpoints in demo mode",
        ],
      }),
    })
    .returning();

  // Insert findings for automated scenarios
  const findingsData: Array<{
    scenarioCode: string;
    result: string;
    actualStatusCode: number | null;
    auditLogFound: boolean;
    alertTriggered: boolean;
    actualResponseSnippet: string;
    findingDescriptionEn: string;
    remediationEn: string;
    riskScore: string;
    isGoLiveBlocker: boolean;
  }> = [
    {
      scenarioCode: "TAMPERED_PACKAGE",
      result: "pass",
      actualStatusCode: 400,
      auditLogFound: false,
      alertTriggered: false,
      actualResponseSnippet: '{"error":"Signature verification failed"}',
      findingDescriptionEn: "System correctly rejected a config package with invalid HMAC signature. Tampered packages are blocked.",
      remediationEn: "No action required. Signature verification is working correctly.",
      riskScore: "0.0",
      isGoLiveBlocker: false,
    },
    {
      scenarioCode: "DUPLICATE_PAYROLL_CLOSE",
      result: "pass",
      actualStatusCode: 409,
      auditLogFound: false,
      alertTriggered: false,
      actualResponseSnippet: '{"error":"Payroll period is already closed"}',
      findingDescriptionEn: "System correctly rejected duplicate close attempt on already-closed payroll period with HTTP 409 Conflict.",
      remediationEn: "No action required. Duplicate close protection is working.",
      riskScore: "0.0",
      isGoLiveBlocker: false,
    },
    {
      scenarioCode: "REPLAY_ATTENDANCE",
      result: "warn",
      actualStatusCode: 201,
      auditLogFound: false,
      alertTriggered: false,
      actualResponseSnippet: "Second punch event accepted with status 201 — no duplicate detection",
      findingDescriptionEn: "DEMO MODE — System accepted duplicate punch events. No unique constraint on (deviceId, employeeId, eventTime). In production with proper constraints, replay attacks should be rejected with 409.",
      remediationEn: "Add unique constraint on punch_events(device_id, employee_id, event_time). Return 409 on duplicate submissions.",
      riskScore: "4.0",
      isGoLiveBlocker: false,
    },
    {
      scenarioCode: "BREAK_GLASS_AUDIT",
      result: "pass",
      actualStatusCode: 201,
      auditLogFound: true,
      alertTriggered: false,
      actualResponseSnippet: '{"id":1,"justification":"SECURITY_TEST","status":"active"}',
      findingDescriptionEn: "Break-glass activation correctly creates an audit log entry. Chain of custody is maintained.",
      remediationEn: "No action required. Break-glass audit trail is functioning correctly.",
      riskScore: "0.0",
      isGoLiveBlocker: false,
    },
    {
      scenarioCode: "MISSING_AUTH_PRIVILEGE_ESCALATION",
      result: "warn",
      actualStatusCode: 201,
      auditLogFound: false,
      alertTriggered: false,
      actualResponseSnippet: "HTTP 201 — license created without authentication",
      findingDescriptionEn: "DEMO MODE — POST /api/admin/license accepted request without authentication (HTTP 201). This is expected in demo mode where no session guards are active. With Keycloak/Passport.js guards, this would return 401/403.",
      remediationEn: "Add session guard middleware to all /api/admin/* routes before go-live. Integrate with Keycloak OIDC. See DEF-001 and DEF-002.",
      riskScore: "9.0",
      isGoLiveBlocker: false, // warn, documented as critical gap but not blocker in demo context
    },
    {
      scenarioCode: "MISSING_AUTH_EXPORT",
      result: "warn",
      actualStatusCode: 200,
      auditLogFound: false,
      alertTriggered: false,
      actualResponseSnippet: "HTTP 200 — export jobs list returned without authentication",
      findingDescriptionEn: "DEMO MODE — GET /api/export-jobs returned HTTP 200 without authentication. Data export endpoints are accessible without credentials. This is expected in demo mode.",
      remediationEn: "Add authentication requirement to all export endpoints before go-live. Consider additional MFA confirmation for bulk exports.",
      riskScore: "7.5",
      isGoLiveBlocker: false,
    },
    {
      scenarioCode: "MASS_ASSIGNMENT",
      result: "pass",
      actualStatusCode: 400,
      auditLogFound: false,
      alertTriggered: false,
      actualResponseSnippet: '{"error":"employeeNumber is required"}',
      findingDescriptionEn: "Extra fields (isAdmin, roleId, systemRole) were safely ignored by Drizzle ORM. No server error, no privilege escalation via mass assignment.",
      remediationEn: "No action required. Continue explicit field extraction in handlers.",
      riskScore: "1.0",
      isGoLiveBlocker: false,
    },
  ];

  for (const fd of findingsData) {
    const scenario = scenarios.find(s => s.scenarioCode === fd.scenarioCode);
    if (!scenario) continue;

    await db.insert(securityTestFindingsTable).values({
      runId: run.id,
      scenarioId: scenario.id,
      result: fd.result,
      actualStatusCode: fd.actualStatusCode,
      auditLogFound: fd.auditLogFound,
      alertTriggered: fd.alertTriggered,
      actualResponseSnippet: fd.actualResponseSnippet,
      findingDescriptionEn: fd.findingDescriptionEn,
      remediationEn: fd.remediationEn,
      riskScore: fd.riskScore,
      isGoLiveBlocker: fd.isGoLiveBlocker,
      executedAt: new Date("2024-12-01T09:30:00Z"),
    });
  }

  // Insert skip findings for manual scenarios
  const manualScenarios = scenarios.filter(s => s.executionType === "manual");
  for (const scenario of manualScenarios) {
    await db.insert(securityTestFindingsTable).values({
      runId: run.id,
      scenarioId: scenario.id,
      result: "skip",
      actualStatusCode: null,
      auditLogFound: false,
      alertTriggered: false,
      actualResponseSnippet: "Manual scenario — not executed in automated run",
      findingDescriptionEn: `Scenario ${scenario.scenarioCode} requires manual execution. See test script for steps.`,
      remediationEn: "Execute this scenario manually and record findings.",
      riskScore: "0.0",
      isGoLiveBlocker: false,
      executedAt: new Date("2024-12-01T09:30:00Z"),
    });
  }

  console.log(`✓ Seeded 1 security test run with ${findingsData.length + manualScenarios.length} findings`);
}

// ─── MAIN ──────────────────────────────────────────────────────────────────────

export async function seedPhase10() {
  console.log("\n🌱 Seeding Phase 10 — Pre-Production Hardening & Pilot Readiness\n");

  await seedGoLiveGates();
  await seedReadinessScorecards();
  await seedPilotDefects();
  await seedMigrationStatus();
  await seedRestoreTestResults();
  await seedUatScripts();
  await seedSecurityTestScenarios();
  await seedSecurityTestRun();

  console.log("\n✅ Phase 10 seed complete\n");
}

// Run if called directly
seedPhase10().catch(console.error);
