import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import employeesRouter from "./employees";
import departmentsRouter from "./departments";
import rolesRouter from "./roles";
import documentsRouter from "./documents";
import approvalsRouter from "./approvals";
import auditRouter from "./audit";
import attendanceRouter from "./attendance";
import attendanceCorrectionsRouter from "./attendanceCorrections";
import devicesRouter from "./devices";
import deviceMappingsRouter from "./deviceMappings";
import alertsRouter from "./alerts";
import usersRouter from "./users";
import shiftsRouter from "./shifts";
import rostersRouter from "./rosters";
import overtimeRulesRouter from "./overtimeRules";
import punchEventsRouter from "./punchEvents";
import leaveTypesRouter from "./leaveTypes";
import leaveBalancesRouter from "./leaveBalances";
import leaveRequestsRouter from "./leaveRequests";
import leaveDelegationsRouter from "./leaveDelegations";
import publicHolidaysRouter from "./publicHolidays";
import salaryGradesRouter from "./salaryGrades";
import payComponentsRouter from "./payComponents";
import payrollPeriodsRouter from "./payrollPeriods";
import payrollRunsRouter from "./payrollRuns";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(dashboardRouter);
router.use(employeesRouter);
router.use(departmentsRouter);
router.use(rolesRouter);
router.use(documentsRouter);
router.use(approvalsRouter);
router.use(auditRouter);
router.use(attendanceRouter);
router.use(attendanceCorrectionsRouter);
router.use(devicesRouter);
router.use(deviceMappingsRouter);
router.use(alertsRouter);
router.use(usersRouter);
router.use(shiftsRouter);
router.use(rostersRouter);
router.use(overtimeRulesRouter);
router.use(punchEventsRouter);
router.use(leaveTypesRouter);
router.use(leaveBalancesRouter);
router.use(leaveRequestsRouter);
router.use(leaveDelegationsRouter);
router.use(publicHolidaysRouter);
router.use(salaryGradesRouter);
router.use(payComponentsRouter);
router.use(payrollPeriodsRouter);
router.use(payrollRunsRouter);

export default router;
