import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import employeesRouter from "./employees";
import departmentsRouter from "./departments";
import rolesRouter from "./roles";
import documentsRouter from "./documents";
import approvalsRouter from "./approvals";
import auditRouter from "./audit";
import attendanceRouter from "./attendance";
import attendanceCorrectionsRouter from "./attendanceCorrections";
import devicesRouter from "./devices";
import deviceMappingsRouter from "./deviceMappings";
import alertsRouter from "./alerts";
import usersRouter from "./users";
import shiftsRouter from "./shifts";
import rostersRouter from "./rosters";
import overtimeRulesRouter from "./overtimeRules";
import punchEventsRouter from "./punchEvents";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(dashboardRouter);
router.use(employeesRouter);
router.use(departmentsRouter);
router.use(rolesRouter);
router.use(documentsRouter);
router.use(approvalsRouter);
router.use(auditRouter);
router.use(attendanceRouter);
router.use(attendanceCorrectionsRouter);
router.use(devicesRouter);
router.use(deviceMappingsRouter);
router.use(alertsRouter);
router.use(usersRouter);
router.use(shiftsRouter);
router.use(rostersRouter);
router.use(overtimeRulesRouter);
router.use(punchEventsRouter);

export default router;
