import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import employeesRouter from "./employees";
import departmentsRouter from "./departments";
import rolesRouter from "./roles";
import documentsRouter from "./documents";
import approvalsRouter from "./approvals";
import auditRouter from "./audit";
import attendanceRouter from "./attendance";
import attendanceCorrectionsRouter from "./attendanceCorrections";
import devicesRouter from "./devices";
import deviceMappingsRouter from "./deviceMappings";
import alertsRouter from "./alerts";
import usersRouter from "./users";
import shiftsRouter from "./shifts";
import rostersRouter from "./rosters";
import overtimeRulesRouter from "./overtimeRules";
import punchEventsRouter from "./punchEvents";
import leaveTypesRouter from "./leaveTypes";
import leaveBalancesRouter from "./leaveBalances";
import leaveRequestsRouter from "./leaveRequests";
import leaveDelegationsRouter from "./leaveDelegations";
import publicHolidaysRouter from "./publicHolidays";
import salaryGradesRouter from "./salaryGrades";
import payComponentsRouter from "./payComponents";
import payrollPeriodsRouter from "./payrollPeriods";
import payrollRunsRouter from "./payrollRuns";
import systemConfigRouter from "./systemConfig";
import militaryRanksRouter from "./militaryRanks";
import orgUnitsRouter from "./orgUnits";
import dutyStationsRouter from "./dutyStations";
import employeePostingsRouter from "./employeePostings";
import employeeTransfersRouter from "./employeeTransfers";
import employeeSecondmentsRouter from "./employeeSecondments";
import securityClearancesRouter from "./securityClearances";
import mobilizationStatusesRouter from "./mobilizationStatuses";
import chainOfCommandRouter from "./chainOfCommand";
import dualAuthRouter from "./dualAuth";
import breakGlassRouter from "./breakGlass";
import adminBackupRouter from "./adminBackup";
import adminBranchesRouter from "./adminBranches";
import adminLicenseRouter from "./adminLicense";
// Phase 5 — Recruitment, Onboarding, Performance, Training, Succession, Self-Service
import jobRequisitionsRouter from "./jobRequisitions.js";
import jobPostingsRouter from "./jobPostings.js";
import applicantsRouter from "./applicants.js";
import applicationsRouter from "./applications.js";
import { interviewScoresRouter } from "./interviewScores.js";
import backgroundChecksRouter from "./backgroundChecks.js";
import jobOffersRouter from "./jobOffers.js";
import employmentContractsRouter from "./employmentContracts.js";
import onboardingTemplatesRouter from "./onboardingTemplates.js";
import employeeOnboardingRouter from "./employeeOnboarding.js";
import probationRecordsRouter from "./probationRecords.js";
import { equipmentIssuancesRouter, idCardRecordsRouter } from "./equipmentIssuances.js";
import { competencyFrameworksRouter, competenciesRouter } from "./competencyFrameworks.js";
import { goalCyclesRouter, employeeGoalsRouter } from "./goalCycles.js";
import { appraisalCyclesRouter, appraisalRecordsRouter, calibrationSessionsRouter } from "./appraisals.js";
import { disciplinaryRecordsRouter, commendationRecordsRouter, promotionRecommendationsRouter } from "./disciplinaryRecords.js";
import {
  trainingProgramsRouter, trainingCoursesRouter, trainingSessionsRouter,
  courseNominationsRouter, trainingAttendanceRouter, certificationsRouter, employeeSkillsRouter,
} from "./trainingRoutes.js";
import { successionPoolsRouter, successionCandidatesRouter, developmentPlansRouter, developmentActivitiesRouter } from "./succession.js";
import { employeeRequestsRouter, announcementsRouter, approvalDelegationsRouter } from "./selfService.js";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(dashboardRouter);
router.use(employeesRouter);
router.use(departmentsRouter);
router.use(rolesRouter);
router.use(documentsRouter);
router.use(approvalsRouter);
router.use(auditRouter);
router.use(attendanceRouter);
router.use(attendanceCorrectionsRouter);
router.use(devicesRouter);
router.use(deviceMappingsRouter);
router.use(alertsRouter);
router.use(usersRouter);
router.use(shiftsRouter);
router.use(rostersRouter);
router.use(overtimeRulesRouter);
router.use(punchEventsRouter);
router.use(leaveTypesRouter);
router.use(leaveBalancesRouter);
router.use(leaveRequestsRouter);
router.use(leaveDelegationsRouter);
router.use(publicHolidaysRouter);
router.use(salaryGradesRouter);
router.use(payComponentsRouter);
router.use(payrollPeriodsRouter);
router.use(payrollRunsRouter);
router.use(systemConfigRouter);
router.use(militaryRanksRouter);
router.use(orgUnitsRouter);
router.use(dutyStationsRouter);
router.use(employeePostingsRouter);
router.use(employeeTransfersRouter);
router.use(employeeSecondmentsRouter);
router.use(securityClearancesRouter);
router.use(mobilizationStatusesRouter);
router.use(chainOfCommandRouter);
router.use(dualAuthRouter);
router.use(breakGlassRouter);
router.use(adminBackupRouter);
router.use(adminBranchesRouter);
router.use(adminLicenseRouter);

// Phase 5
router.use("/job-requisitions", jobRequisitionsRouter);
router.use("/job-postings", jobPostingsRouter);
router.use("/applicants", applicantsRouter);
router.use("/applications", applicationsRouter);
router.use("/interview-scores", interviewScoresRouter);
router.use("/background-checks", backgroundChecksRouter);
router.use("/job-offers", jobOffersRouter);
router.use("/employment-contracts", employmentContractsRouter);
router.use("/onboarding-templates", onboardingTemplatesRouter);
router.use("/employee-onboarding", employeeOnboardingRouter);
router.use("/probation-records", probationRecordsRouter);
router.use("/equipment-issuances", equipmentIssuancesRouter);
router.use("/id-card-records", idCardRecordsRouter);
router.use("/competency-frameworks", competencyFrameworksRouter);
router.use("/competencies", competenciesRouter);
router.use("/goal-cycles", goalCyclesRouter);
router.use("/employee-goals", employeeGoalsRouter);
router.use("/appraisal-cycles", appraisalCyclesRouter);
router.use("/appraisal-records", appraisalRecordsRouter);
router.use("/calibration-sessions", calibrationSessionsRouter);
router.use("/disciplinary-records", disciplinaryRecordsRouter);
router.use("/commendation-records", commendationRecordsRouter);
router.use("/promotion-recommendations", promotionRecommendationsRouter);
router.use("/training-programs", trainingProgramsRouter);
router.use("/training-courses", trainingCoursesRouter);
router.use("/training-sessions", trainingSessionsRouter);
router.use("/course-nominations", courseNominationsRouter);
router.use("/training-attendance", trainingAttendanceRouter);
router.use("/certifications", certificationsRouter);
router.use("/employee-skills", employeeSkillsRouter);
router.use("/succession-pools", successionPoolsRouter);
router.use("/succession-candidates", successionCandidatesRouter);
router.use("/development-plans", developmentPlansRouter);
router.use("/development-activities", developmentActivitiesRouter);
router.use("/employee-requests", employeeRequestsRouter);
router.use("/announcements", announcementsRouter);
router.use("/approval-delegations", approvalDelegationsRouter);

// Phase 6 — Document Management, Reporting, Notifications, Deployment Ops
import documentCategoriesRouter from "./documentCategories.js";
import enterpriseDocumentsRouter from "./enterpriseDocuments.js";
import documentTemplatesRouter from "./documentTemplates.js";
import reportDefinitionsRouter from "./reportDefinitions.js";
import savedReportFiltersRouter from "./savedReportFilters.js";
import reportSchedulesRouter from "./reportSchedules.js";
import reportOutputsRouter from "./reportOutputs.js";
import notificationsRouter from "./notifications.js";
import notificationPreferencesRouter from "./notificationPreferences.js";
import escalationRulesRouter from "./escalationRules.js";
import approvalInboxRouter from "./approvalInbox.js";
import healthChecksRouter from "./healthChecks.js";
import updatePackagesRouter from "./updatePackages.js";
import deploymentEventsRouter from "./deploymentEvents.js";
import installationReadinessRouter from "./installationReadiness.js";

router.use("/document-categories", documentCategoriesRouter);
router.use("/enterprise-documents", enterpriseDocumentsRouter);
router.use("/document-templates", documentTemplatesRouter);
router.use("/report-definitions", reportDefinitionsRouter);
router.use("/saved-report-filters", savedReportFiltersRouter);
router.use("/report-schedules", reportSchedulesRouter);
router.use("/report-outputs", reportOutputsRouter);
router.use("/notifications", notificationsRouter);
router.use("/notification-preferences", notificationPreferencesRouter);
router.use("/escalation-rules", escalationRulesRouter);
router.use("/approval-inbox", approvalInboxRouter);
router.use("/health-checks", healthChecksRouter);
router.use("/update-packages", updatePackagesRouter);
router.use("/deployment-events", deploymentEventsRouter);
router.use("/installation-readiness", installationReadinessRouter);

// Phase 7A — Workforce Analytics + Report Builder + Exports
import analyticsRouter from "./analytics.js";
import reportBuilderConfigsRouter from "./reportBuilderConfigs.js";
import exportJobsRouter from "./exportJobs.js";
import scheduledExportsRouter from "./scheduledExports.js";

router.use(analyticsRouter);
router.use(reportBuilderConfigsRouter);
router.use(exportJobsRouter);
router.use(scheduledExportsRouter);

// Phase 7B — Integration Administration Center
import integrationConnectorsRouter from "./integrationConnectors.js";
import integrationRetryQueueRouter from "./integrationRetryQueue.js";
import integrationEventsRouter from "./integrationEvents.js";
// Phase 7C — Local AI Layer
import localAiRouter from "./localAi.js";

router.use(integrationConnectorsRouter);
router.use(integrationRetryQueueRouter);
router.use(integrationEventsRouter);
router.use(localAiRouter);

export default router;
